name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deployment to Production
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Copy files to Production Server
              uses: appleboy/scp-action@master
              with:
                  HOST: ${{ secrets.SERVER_IP }}
                  PORT: ${{ secrets.SERVER_PORT }}
                  USERNAME: ${{ secrets.SERVER_USERNAME }}
                  PASSWORD: ${{ secrets.SERVER_PASSWORD }}
                  TARGET: ${{ secrets.TARGET }}
                  SOURCE: .dist/*
                  STRIP_COMPONENTS: 1
